### ISSUE TITLE
What cloud provider to use for production?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/playground#25]
@ashirrwad set it up on a free EC2 (AWS) instance (see http://34.235.154.182).

For long-term production, is there a preference for any other cloud provider? I have (mostly great) experience with DigitalOcean, but they don't have a free tier, so I recommend going with a provider that has a free tier and AWS seems fine to me.

Once we agree on the provider, the admins should create a dedicated fortran-lang account with that provider.

**Comment by ashirrwad** [comment]
Just an edit I changed the IP for it to http://54.145.137.3/ , for anyone that wants to access it. Also note, it's an old build and the final app hasn't been merged yet.

**Comment by awvwgk** [comment]
A quick search pointed me to this resource https://github.com/cloudcommunity/Cloud-Free-Tier-Comparison.

**Comment by ashirrwad** [comment]
One more suggestion, we can host the frontend via github pages( see ashirrwad.github.io/playground), and dedicate the cloud vm just for our flask api. This way we will just have to maintain the backend as github pages will take care of our react build.

**Comment by milancurcic** [comment]
@ashirrwad I like that idea, that makes one less server process needed to run on the VM (better for the CPU budget on the free tier), and easier to maintain. I'll then set up play-api.fortran-lang.org subdomain to point to the Python backend, and we can then update the API URL in the frontend to point to play-api.fortran-lang.org rather than hardcoding the IP address.

**Comment by certik** [comment]
Yes, we should host as much as possible using static pages.

**Comment by milancurcic** [comment]
Currently using AWS EC2 for the Python backend and GitHub Pages for the frontend. Please re-open this issue you want to discuss it further.
