### ISSUE TITLE
What OS to use for production?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/playground#26]
Some factors to consider:

* Easy access to software we need (Python, Node.js, Docker)
* Widely used for easier maintenance
* Long term support (for security updates and similar)

What do you all think about Ubuntu 22.04 LTS (server variant) which I think checks the above boxes?

**Comment by awvwgk** [comment]
I'm not a big fan of Ubuntu, but it should work, however I would generally be in favor of Red Head variant. I think Bálint @aradi is using [AlmaLinux](https://almalinux.org/) for our buildbot at DFTB+.

**Comment by awvwgk** [comment]
> Where will it be hosted?

See https://github.com/fortran-lang/playground/issues/25 for the discussion on hosting.

**Comment by certik** [comment]
So I would first resolve #25, and then choose the system.

**Comment by milancurcic** [comment]
I was setting up the backend and am most familiar with Ubuntu, so Ubuntu 22.04 LTS server is what we currently use in production. Please reopen this if you want to discuss it further.
