### ISSUE TITLE
What Python server to use in production?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/playground#27]
@ashirrwad what are you using in your current deployment on AWS?

I've been using both [gunicorn](https://gunicorn.org/) (WSGI) and [uvicorn](https://www.uvicorn.org/) (ASGI) without problems. Flask needs a WSGI server. Uvicorn can support WSGI as a special case, but I don't see a reason to do that if gunicorn works fine.

Any preference?

**Comment by ashirrwad** [comment]
I'm using gunicorn to deploy it and it seems to work fine.
