### ISSUE TITLE
How to reverse proxy and SSL encrypt?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/playground#28]
The traditional common solution has been to run NGINX as a reverse proxy to Node.js and Python servers that are serving on their respective ports, and to periodically get SSL certificates from Let's Encrypt. The latter can be further automated with [certbot](https://certbot.eff.org/).

But, NGINX is also known to be notoriously difficult to configure beyond the sane and minimal defaults. I recently discovered and have transitioned to [Caddy](https://caddyserver.com/), a production-ready server that is extremely easy to run (minimal configuration needed) and automatically provides an SSL cert. Caddy is my recommendation for this project as well.

What do you think?

**Comment by ashirrwad** [comment]
I'll try experimenting with it on my instance and see how it works out.

**Comment by milancurcic** [comment]
Using Caddy as the simplest production-ready solution, as per #32.
