### ISSUE TITLE
How to persist the server between reboots in production?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/playground#29]
We need to ensure that all servers (Python, Node.js, reverse proxy server) start on boot. I've been using systemd for this, and I think it's a common solution for this problem. Is there a better way to do this?

Docker daemon runs in its own systemd service so nothing for us to do there.

**Comment by awvwgk** [comment]
systemd seems like the choice most Linux distributions are opting for. There is also extensive documentation available, like in the Arch Wiki: https://wiki.archlinux.org/title/Systemd.

**Comment by milancurcic** [comment]
Fixed by #32.
