### ISSUE TITLE
At what subdomain should we host the playground?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/playground#30]
Rust has https://play.rust-lang.org. I think it's nice and short.

What do you think about play.fortran-lang.org for the Fortran playground?

**Comment by everythingfunctional** [comment]
my vote is play.fortran-lang.org

**Comment by awvwgk** [comment]
I like `play.fortran-lang.org`, alternatives might be `code.fortran-lang.org` or `try.fortran-lang.org`.

**Comment by milancurcic** [comment]
Implemented with #36.
