### ISSUE TITLE
Linking code samples from FortranTipBrowser

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/playground#51]
From #49 by @zmoon:

> Wondering about linking code samples in [FortranTipBrowser](https://zmoon.github.io/FortranTipBrowser/) to this playground. I guess what would be more useful for that would be being able to pass the script in URL query parameters, as is possible with Godbolt.

**Comment by zmoon** [comment]
In case it's not clear this would be for like an "Open in Fortran Playground" link.
