### ISSUE TITLE
Playground"OCI runtime exec failed: exec failed: unable to start container process: read init-p: connection reset by peer: unknown"  returning as Output ( As of oct 21 16:00 UTC) 

### ISSUE THREAD

**Issue by henilp105** [fortran-lang/playground#58]
This is to inform that the Playground is Returning only empty quotes as output to **any** fortran program . It seems that there is some server side error as I also tried the same with the curl (to backend API) .

Thanks and Regards,
Henil 

CC @awvwgk @milancurcic

**Comment by milancurcic** [comment]
Thanks, I'll check.

**Comment by henilp105** [comment]
Thanks sir, It is now working fine.

**Comment by milancurcic** [comment]
I was able to reproduce and found no related errors from the Python server, so I suspect something broke inside the container (a creative user could certainly break it with Fortran code and make it return an empty string). I restarted the systemd service of the backend and it seems to work now. I suspect that addressing #54 should help with these kinds of issues.

**Comment by henilp105** [comment]
This is to inform that the Playground is Returning "OCI runtime exec failed: exec failed: unable to start container process: read init-p: connection reset by peer: unknown" as output to any fortran program . It seems that there is some server side error as I also tried the same with the curl (to backend API) .

Thanks and Regards,
Henil

CC @awvwgk @milancurcic

**Comment by milancurcic** [comment]
Thanks, I rebooted the VM, it seems to work now.

**Comment by henilp105** [comment]
Thanks @milancurcic sir.
