### ISSUE TITLE
Give ability to change theme of the editor

### ISSUE THREAD

**Issue by uNouss** [fortran-lang/playground#60]
https://github.com/fortran-lang/playground/blob/0b87b12fd6b07b8545f9c7cb84388cc24fedc0dc/frontend/src/Editor.js#L5

Can be changed to the light theme, because in some situations the dark theme can be unreadable.

It would be useful to have an option to choose light or dark mode depending on your preferences.

### Suggestions

for example by using this theme:
```jsx
import "ace-builds/src-noconflict/theme-solarized_light";
```

**Comment by Kartikey353** [comment]
Assign me this issue

**Comment by Jay9874** [comment]
@milancurcic  @Kartikey353  What is the progress for in the theme. I am a experienced in React framework and have build projects using crud operation. I want to join to in the fortran playground project. I would love to hear from you back..

**Comment by milancurcic** [comment]
Hi @Jay9874, welcome and thank you for your interest. I don't know if @Kartikey353 has any work in progress on this, there's no PR open at least. If you'd like to tackle this, that would be very welcome.

**Comment by milancurcic** [comment]
Hi @rajkumardongre, yes the issue is open and a PR would be very welcome!
