### ISSUE TITLE
Replace icon images with Bootstrap Icons

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [fortran-lang/playground#64]
A tangential comment about icons: I noticed that whenever we add new icons we introduce new image files for the icons. Would it not be a better solution to rely on an icons library? Since we're using Bootstrap for UI elements, we could use Bootstrap Icons library for button icons. Nothing to do about this in this PR, just wanted to bring it up.

_Originally posted by @milancurcic in https://github.com/fortran-lang/playground/issues/63#issuecomment-1448717264_

**Comment by rajkumardongre** [comment]
Thanks @Shaikh-Ubaid for raising this issue, i want to work on this issue can you assign this to me

**Comment by Shaikh-Ubaid** [comment]
@rajkumardongre Thank you for your interest in working on this issue. I'm glad to hear that you want to contribute. Unfortunately, I don't have the access to assign the issue to you. However, I will bring your offer to Milan's attention so they can consider assigning the issue to you. Thank you again for your willingness to contribute.

@milancurcic could you assign this issue to @rajkumardongre, please?

**Comment by rajkumardongre** [comment]
Thank you so much for your prompt response, @Shaikh-Ubaid.  I appreciate your efforts in bringing my interest to @milancurcic  attention.
As suggested, I have [Replace all icon Images With Bootstrap Icons](https://github.com/fortran-lang/playground/pull/63/commits/adc0d54b971a2e4efa04e6d880abfb05a6561e5e), and made a PR, could you please review it.

Thank you again for your help and support.

**Comment by Shaikh-Ubaid** [comment]
For layout icons, maybe we can use https://icons.getbootstrap.com/icons/phone/ and https://icons.getbootstrap.com/icons/phone-landscape/?

**Comment by rajkumardongre** [comment]
Thank you for recommending the use of icons from https://icons.getbootstrap.com/icons/phone/ and https://icons.getbootstrap.com/icons/phone-landscape/ in our layout. However, I am concerned that users may mistake the mobile button for something related to Android, leading to confusion.

**Comment by rajkumardongre** [comment]
what about  [this](https://icons.getbootstrap.com/icons/phone-flip/) icon, is it good?
![image](https://user-images.githubusercontent.com/77038993/224330202-44c0f7b8-0e1f-471f-b1ee-0c4f21014813.png)

**Comment by milancurcic** [comment]
@rajkumardongre I did see that one during my brief search. I don't think it's appropriate for this because it suggests flipping the phone.

Another alternative is to not rely on icons for this but use plain Unicode text. For example, we could use [◫](https://www.compart.com/en/unicode/U+25EB) for vertically split layout and the same symbol but CSS-rotated by 90 degrees for horizontally spliy layout.

**Comment by rajkumardongre** [comment]
@milancurcic Your suggestion of using plain Unicode text is a great alternative. Using symbols like ◫ for vertical split layout and rotating the same symbol for horizontal split layout is a clever solution.

**Comment by rajkumardongre** [comment]
After doing some research, I discovered [this](https://www.compart.com/en/unicode/U+229F). I believe that by using this, we may not even need to use CSS anymore.

for vertical split we can use [this](https://www.compart.com/en/unicode/U+25EB)
![image](https://user-images.githubusercontent.com/77038993/224368672-d3e46d67-6326-4b7e-940a-fcbc70c55a38.png)

and for Horizontal split we can use [this](https://www.compart.com/en/unicode/U+229F)
![image](https://user-images.githubusercontent.com/77038993/224369206-254e833b-8428-4d1a-810f-744c47b39e99.png)

**Comment by rajkumardongre** [comment]
Hello i have made the required changes, [here](https://github.com/fortran-lang/playground/pull/66), could you please review the code

**Comment by rajkumardongre** [comment]
@milancurcic @Shaikh-Ubaid Are there any other changes, I should work on

**Comment by ubaidsk** [comment]
Closing as fixed in [Replace all icon Images With Bootstrap Icons](https://github.com/fortran-lang/playground/pull/63/commits/adc0d54b971a2e4efa04e6d880abfb05a6561e5e), https://github.com/fortran-lang/playground/pull/66.
