### ISSUE TITLE
Add more info on flask server to readme

### ISSUE THREAD

**Issue by everythingfunctional** [fortran-lang/playground#9]
Quoting @milancurcic comment from #2

> Add a note on what address and port will the server run and give a minimal request example (e.g. curl -X POST ...) so the user knows how to try it out.

**Comment by ashirrwad** [comment]
I'm just dropping the curl request exampple on this issue, meanwhile. I'll push it with the next PR, if that's okay.
`
curl --location --request POST '127.0.0.1:5000/run' \
--header 'Content-Type: application/json' \
--data-raw '{
  "code": "program hello\nprint *, \"Hello World New Line\"\nprint *, \"Hello Mars\"\nend program hello"
}
'
`
Please use proper formatting on code key. It's easier to do it with the editor.
